version: '3'
services:
  db:
    container_name: "db"
    build: ./db
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - local-net
    restart: always
    tty: true

  response-server:
    build: .
    ports:
      - "8080:80"
    links:
      - db
    networks:
      - local-net

networks:
  local-net:
    driver: bridge